### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by mattloose** [BiGzGiB/IsoFinder#1]
Hi YC,

Would you mind updating the ReadMe file when you get a chance?

Thanks

**Comment by ghost** [comment]
Hi Matt,

I've updated the README file. I've noticed some grammar mistakes after pushing it, sorry about that.

Please let me know if there is anything else to clarify or change.

Thanks

**Comment by mattloose** [comment]
Thanks - you can of course always update it if you need to!
